#ifndef	_APP_EDPMULTICORE_H
#define	_APP_EDPMULTICORE_H

#include	"E7602_PG_Application.h"

enum{
	EDPMC_REG_VERSION					= 0x00,
	EDPMC_REG_INPUT_MODE				= 0x01,
	EDPMC_REG_VIDEO_MODE				= 0x02,		//	REMOVED
	EDPMC_REG_EDID_READ					= 0x03,
	EDPMC_REG_CORE_RESET				= 0x04,
	EDPMC_REG_CORE_ENABLE				= 0x05,
	EDPMC_REG_INPUT_SOURCE				= 0x06,
	EDPMC_REG_LINK_STATUS_0				= 0x07,
	EDPMC_REG_LINK_STATUS_1				= 0x08,
	EDPMC_REG_LINK_STATUS_2				= 0x09,
	EDPMC_REG_ADDRESS_BYTE_0			= 0x0A,
	EDPMC_REG_ADDRESS_BYTE_1			= 0x0B,
	EDPMC_REG_ADDRESS_BYTE_2			= 0x0C,
	EDPMC_REG_ADDRESS_BYTE_3			= 0x0D,
	EDPMC_REG_SINK_REG_ACCESS_DPCD		= 0x0E,
	EDPMC_REG_DATA_SIZE					= 0x0F,
	EDPMC_REG_DATA_BYTE_0				= 0x10,
	EDPMC_REG_DATA_BYTE_1				= 0x11,
	EDPMC_REG_DATA_BYTE_2				= 0x12,
	EDPMC_REG_DATA_BYTE_3				= 0x13,
	EDPMC_REG_DATA_BYTE_4				= 0x14,
	EDPMC_REG_DATA_BYTE_5				= 0x15,
	EDPMC_REG_DATA_BYTE_6				= 0x16,
	EDPMC_REG_DATA_BYTE_7				= 0x17,
	EDPMC_REG_DATA_BYTE_8				= 0x18,
	EDPMC_REG_DATA_BYTE_9				= 0x19,
	EDPMC_REG_DATA_BYTE_10				= 0x1A,
	EDPMC_REG_DATA_BYTE_11				= 0x1B,
	EDPMC_REG_DATA_BYTE_12				= 0x1C,
	EDPMC_REG_DATA_BYTE_13				= 0x1D,
	EDPMC_REG_DATA_BYTE_14				= 0x1E,
	EDPMC_REG_DATA_BYTE_15				= 0x1F,
	EDPMC_REG_AUX_INIT					= 0x20,
	EDPMC_REG_AUX_TRANSACTION_STATUS	= 0x21,
	EDPMC_REG_EDID_ADDRESS_SPACE_SELECT	= 0x22,
	EDPMC_REG_EDID_READ_STATUS			= 0x23,

	EDPMC_REG_H_RESOLUTION_LOW			= 0x26,
	EDPMC_REG_H_RESOLUTION_HIGH			= 0x27,
	EDPMC_REG_V_RESOLUTION_LOW			= 0x28,
	EDPMC_REG_V_RESOLUTION_HIGH			= 0x29,
	EDPMC_REG_INPUT_FRAMERATE			= 0x2A,
	EDPMC_REG_OUTPUT_FRAMERATE			= 0x2B,
	EDPMC_REG_RGB_DEPTH					= 0x2C,
	EDPMC_REG_H_BLANK_LOW				= 0x2D,
	EDPMC_REG_H_BLANK_HIGH				= 0x2E,
	EDPMC_REG_V_BLANK_LOW				= 0x2F,
	EDPMC_REG_V_BLANK_HIGH				= 0x30,

	EDPMC_REG_EDID_START_ADRS			= 0x80,
};

u8 eDPMC_GetVersion(u8 *pData);
u8 eDPMC_GetVideoInputType(u8 *pData);
u8 eDPMC_SetEdidReadEnable(u8 channel);
u8 eDPMC_SetCoreReset(u8 channel);
u8 eDPMC_GetLinkStatus(u8 channel, u8 *pData);
u8 eDPMC_SetInputResolution(void *pVoid);
u8 eDPMC_GetEDID(u8 channel, u8 *pData);
u8 eDPMC_ReadAUX(u8 channel, u32 adrs, u8 *pData, u8 size);
u8 eDPMC_WriteAUX(u8 channel, u32 adrs, u8 *pData, u8 size);

#endif	// _APP_EDPMULTICORE_H