#ifndef	_CMD_RXDPCORE_H
#define	_CMD_RXDPCORE_H

#include	"E7602_PG_Application.h"

extern	const	commandList_t	cmdList_RXDPCore[];

enum{
	GPIO_MTP_TO_TOUCH_RESET_L_CONN		= 0,
	SPI0_MTP_TO_TOUCH_SCLK_CONN,
	SPI0_MTP_FROM_TOUCH_MISO_CONN,
	SPI0_MTP_TO_TOUCH_MOSI_CONN,
	GPIO_MTP_FROM_TOUCH_INT0_L_CONN,
	IO_KRAKEN_TO_TOUCH_AID_CONN,
	SWD_NUB_TO_PMU_TOUCH_SWCLK_CONN,
	SPI0_MTP_TO_TOUCH_SSIN_CONN,
	GPIO_SEQ_PMU_TO_DISPLAY_RESET_L,
	IO_TOUCH_TO_MANY_SCAN_ACTIVE,
	I2C_SDA_TOUCH_EEPROM_1V8,
	I2C_SCL_TOUCH_EEPROM_1V8,
	GPIO_MTP_FROM_TOUCH_INT1_L_CONN,
	GPIO_AP_FROM_DISPLAY_PANEL_ID_CONN,
	SWD_NUB_BI_TOUCH_SWDIO_CONN,
	IO_AOP_TO_TOUCH_BSYNC0_CONN_1,
	IO_AOP_TO_TOUCH_BSYNC1_CONN_1,
	IO_AOP_TO_TOUCH_BSYNC0_CONN_2,
	IO_AOP_TO_TOUCH_BSYNC1_CONN_2,
	FRAME_GND_MEAS_OUT,
	FTP_KELVIN_DG_0,
	FTP_KELVIN_DG_1,
	POGO_VTP_DUT_GND_0,
	DC_IO_AOP_PMU_DPMIC_TO_DISPLAY_PANICB_L,
};

#endif	// _CMD_RXDPCORE_H