#ifndef	_HSP_MEMORYCONTROL_H
#define	_HSP_MEMORYCONTROL_H

#include	"HSP.h"

#define	MEMCTRL_SDRAM_TIMEOUT								0xFFFF

#define MEMCTRL_REFRESH_COUNT								824

#define MEMCTRL_SDRAM_MODEREG_BURST_LENGTH_1				0x0000
#define MEMCTRL_SDRAM_MODEREG_BURST_LENGTH_2				0x0001
#define MEMCTRL_SDRAM_MODEREG_BURST_LENGTH_4				0x0002
#define MEMCTRL_SDRAM_MODEREG_BURST_LENGTH_8				0x0004
#define MEMCTRL_SDRAM_MODEREG_BURST_TYPE_SEQUENTIAL			0x0000
#define MEMCTRL_SDRAM_MODEREG_BURST_TYPE_INTERLEAVED		0x0008
#define MEMCTRL_SDRAM_MODEREG_CAS_LATENCY_2					0x0020
#define MEMCTRL_SDRAM_MODEREG_CAS_LATENCY_3					0x0030
#define MEMCTRL_SDRAM_MODEREG_OPERATING_MODE_STANDARD		0x0000
#define MEMCTRL_SDRAM_MODEREG_WRITEBURST_MODE_PROGRAMMED	0x0000
#define MEMCTRL_SDRAM_MODEREG_WRITEBURST_MODE_SINGLE		0x0200

u8 MEMCTRL_NAND_StatusCheck();
u8 MEMCTRL_NAND_AdrsCalculator(u32 pageNo, NAND_AddressTypeDef *pAdrs);
u8 MEMCTRL_Init();
u8 MEMCTRL_SDRAM_Clear();

#endif	//	_HSP_MEMORYCONTROL_H
