#ifndef	_BSP_TASK_H
#define	_BSP_TASK_H

#include	"BSP.h"

#if	(BSP_USE_RTOS)

enum{
	BSP_TASK_PRIORITY_IDLE			= 1,
	BSP_TASK_PRIORITY_VERY_LOW,
	BSP_TASK_PRIORITY_LOW,
	BSP_TASK_PRIORITY_MEDIUM,
	BSP_TASK_PRIORITY_HIGH,
	BSP_TASK_PRIORITY_VERY_HIGH,
	BSP_TASK_PRIORITY_CRITICAL,
	BSP_TASK_PRIORITY_VERY_CRITICAL,
};

void BSP_Task_SystemReboot();
u8 BSP_Task_Init();

#endif	//	BSP_USE_RTOS

#endif	//	_BSP_TASK_H